choco -y install disableuac
choco -y install driverbooster
choco -y install vlc
choco -y install firefox
choco -y install filezilla
choco -y install ccleaner 
choco -y install jdk7
choco -y install jdk
choco -y install jre8
choco -y install intellijidea-community
choco -y install vcredist2015
choco -y install vcredist2013
choco -y install visualstudio2015community
choco -y install qt-sdk-windows-x64-mingw_opengl_sjlj
choco -y install adobereader
choco -y install putty
choco -y install vim
choco -y install conemu
choco -y install cmder
choco -y install python
choco -y install procexp
choco -y install paint.net
choco -y install mysql.workbench
choco -y install wget
choco -y install curl
choco -y install sublimetext2
choco -y install sublimetext2.packagecontrol
choco -y install sublimetext3
choco -y install sublimetext3.packagecontrol
choco -y install cygwin
choco -y install sourcetree
choco -y install vcredist2013
choco -y install windbg
choco -y install steam
choco -y install git
choco -y install beyondcompare
choco -y install tightvnc

choco -y install spacesniffer
choco -y install dependencywalker
choco -y install linkshellextension

choco -y install minecraft

choco -y install 7zip